nodeLinker: node-modules

# Force HTTPS for GitHub git dependencies (fixes CI permission errors)
gitUrlSubstitution:
  "ssh://git@github.com/": "https://github.com/"
  "git@github.com:": "https://github.com/"
