name: Build Project

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Build project
        run: pnpm build
