name: Manual Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: string
        description: 'Must be: patch, minor, major, pre* or <version>'
        required: true
        default: 'patch'

jobs:
  manual-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup GIT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        working-directory: packages/baileys
        run: pnpm exec release-it --increment ${{ github.event.inputs.increment }}
