name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: pnpm test
